pipelines:
  custom: # Manual trigger in Bitbucket
    Ubuntu_Firefox_Grid:
      - step:
          name: Ubuntu Firefox Grid
          image: maven:3.9.5-jdk-21 # Combined Maven and JDK image
          services:
            - docker # Required for docker compose
          script:
            - git checkout $BITBUCKET_BRANCH # Equivalent to actions/checkout
            - docker compose -f src/main/resources/docker-compose/selenium4.yml up --scale chrome=0 --scale edge=0 --scale firefox=10 -d
            - docker ps # Check running containers
            - mvn -e test "-DdefaultElementIdentificationTimeout=5" "-DsetParallelMode=DYNAMIC" "-DsetParallel=METHODS" "-DretryMaximumNumberOfAttempts=1" "-DexecutionAddress=localhost:4444" "-DtargetOperatingSystem=LINUX" "-DtargetBrowserName=firefox" "-DheadlessExecution=true" "-DgenerateAllureReportArchive=true" -Dtest=SampleTest,SampleTest1
            - pipe: codecov/codecov:v2
              variables:
                CODECOV_TOKEN: $CODECOV_TOKEN # Assumes you have CODECOV_TOKEN set as a Bitbucket variable
                FILES: ./target/jacoco/jacoco.xml
            - pipe: atlassian/upload-file:0.3.2 # For uploading artifacts
              variables:
                FILENAME: allure-report/*.html
                DESTINATION: Ubuntu_Firefox_Grid_Allure
            - pipe: junit-report:0.3.0 # For test summary
              variables:
                JUNIT_REPORTS: "target/surefire-reports/junitreports/TEST-*.xml"

    Ubuntu_Chrome_Grid:
      - step:
          name: Ubuntu Chrome Grid
          image: maven:3.9.5-jdk-21
          services:
            - docker
          script:
            - git checkout $BITBUCKET_BRANCH
            - docker compose -f src/main/resources/docker-compose/selenium4.yml up --scale chrome=10 --scale edge=0 --scale firefox=0 -d
            - docker ps
            - mvn -e test "-DdefaultElementIdentificationTimeout=5" "-DsetParallelMode=DYNAMIC" "-DsetParallel=METHODS" "-DretryMaximumNumberOfAttempts=1" "-DexecutionAddress=localhost:4444" "-DtargetOperatingSystem=LINUX" "-DtargetBrowserName=chrome" "-DheadlessExecution=true" "-DgenerateAllureReportArchive=true" -Dtest=SampleTest2,SampleTest3
            - pipe: codecov/codecov:v2
              variables:
                CODECOV_TOKEN: $CODECOV_TOKEN
                FILES: ./target/jacoco/jacoco.xml
            - pipe: atlassian/upload-file:0.3.2
              variables:
                FILENAME: allure-report/*.html
                DESTINATION: Ubuntu_Chrome_Grid_Allure
            - pipe: junit-report:0.3.0
              variables:
                JUNIT_REPORTS: "target/surefire-reports/junitreports/TEST-*.xml"
    Ubuntu_Edge_Grid:
      - step:
          name: Ubuntu Edge Grid
          image: maven:3.9.5-jdk-21
          services:
            - docker
          script:
            - git checkout $BITBUCKET_BRANCH
            - docker compose -f src/main/resources/docker-compose/selenium4.yml up --scale chrome=0 --scale edge=10 --scale firefox=0 -d
            - docker ps
            - mvn -e test "-DdefaultElementIdentificationTimeout=5" "-DsetParallelMode=DYNAMIC" "-DsetParallel=METHODS" "-DretryMaximumNumberOfAttempts=1" "-DexecutionAddress=localhost:4444" "-DtargetOperatingSystem=LINUX" "-DtargetBrowserName=MicrosoftEdge" "-DheadlessExecution=true" "-DgenerateAllureReportArchive=true" -Dtest=SampleTest4,SampleTest5
            - pipe: codecov/codecov:v2
              variables:
                CODECOV_TOKEN: $CODECOV_TOKEN
                FILES: ./target/jacoco/jacoco.xml
            - pipe: atlassian/upload-file:0.3.2
              variables:
                FILENAME: allure-report/*.html
                DESTINATION: Ubuntu_Edge_Grid_Allure
            - pipe: junit-report:0.3.0
              variables:
                JUNIT_REPORTS: "target/surefire-reports/junitreports/TEST-*.xml"