name: Ubuntu-Browsers

on:
  workflow_dispatch:  # Manual trigger from GitHub Actions UI
jobs:
  Ubuntu_Firefox_Grid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Native Selenium Grid
        run: docker compose -f src/main/resources/docker-compose/selenium4.yml up --scale chrome=0 --scale edge=0 --scale firefox=10 -d
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.5
      - name: Check running containers
        run: docker ps
      - name: Run tests
        continue-on-error: true
        run: mvn -e test "-DdefaultElementIdentificationTimeout=5" "-DsetParallelMode=DYNAMIC" "-DsetParallel=METHODS" "-DretryMaximumNumberOfAttempts=1" "-DexecutionAddress=localhost:4444" "-DtargetOperatingSystem=LINUX" "-DtargetBrowserName=firefox" "-DheadlessExecution=true" "-DgenerateAllureReportArchive=true" -Dtest=SampleTest,SampleTest1
      - name: Upload coverage to Codecov
        uses:  codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          files: ./target/jacoco/jacoco.xml
          verbose: true
      - name: Upload Allure Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Ubuntu_Firefox_Grid_Allure
          path: "allure-report/*.html"
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "target/surefire-reports/junitreports/TEST-*.xml"
        if: always()
  Ubuntu_Chrome_Grid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Native Selenium Grid
        run: docker compose -f src/main/resources/docker-compose/selenium4.yml up --scale chrome=10 --scale edge=0 --scale firefox=0 -d
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.5
      - name: Check running containers
        run: docker ps
      - name: Run tests
        continue-on-error: true
        run: mvn -e test "-DdefaultElementIdentificationTimeout=5" "-DsetParallelMode=DYNAMIC" "-DsetParallel=METHODS" "-DretryMaximumNumberOfAttempts=1" "-DexecutionAddress=localhost:4444" "-DtargetOperatingSystem=LINUX" "-DtargetBrowserName=chrome" "-DheadlessExecution=true" "-DgenerateAllureReportArchive=true" -Dtest=-Dtest=SampleTest2,SampleTest3     
        
      - name: Upload coverage to Codecov
        uses:  codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          files: ./target/jacoco/jacoco.xml
          verbose: true
      - name: Upload Allure Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Ubuntu_Chrome_Grid_Allure
          path: "allure-report/*.html"
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "target/surefire-reports/junitreports/TEST-*.xml"
        if: always()
  Ubuntu_Edge_Grid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Native Selenium Grid
        run: docker compose -f src/main/resources/docker-compose/selenium4.yml up --scale chrome=0 --scale edge=10 --scale firefox=0 -d
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'maven'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.5
      - name: Check running containers
        run: docker ps
      - name: Run tests
        continue-on-error: true
        run: mvn -e test "-DdefaultElementIdentificationTimeout=5" "-DsetParallelMode=DYNAMIC" "-DsetParallel=METHODS" "-DretryMaximumNumberOfAttempts=1" "-DexecutionAddress=localhost:4444" "-DtargetOperatingSystem=LINUX" "-DtargetBrowserName=MicrosoftEdge" "-DheadlessExecution=true" "-DgenerateAllureReportArchive=true" -Dtest=SampleTest4,SampleTest5     
      - name: Upload coverage to Codecov
        uses:  codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          files: ./target/jacoco/jacoco.xml
          verbose: true
      - name: Upload Allure Report as Pipeline Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Ubuntu_Edge_Grid_Allure
          path: "allure-report/*.html"
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "target/surefire-reports/junitreports/TEST-*.xml"
        if: always()
      - name: Send Allure Report via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{secrets.smtp.gmail.com}}
          server_port: ${{secrets.587}}
          username: ${{ secrets.olaismail613@gmail.com}}
          password: ${{secrets.2012019Ali@}}
          subject: "Allure Test Report"
          body: |
            Hi,
            
            Please find attached the Allure reports for the recent test run on Firefox, Chrome, and Edge.
            
            Best regards,
            CI/CD Team
          to: ${{secrets.olaismail613@gmail.com}}}
          from: ${{secrets.olaismail613@gmail.com}}}
          attachments: |
            allure-reports/Ubuntu_Firefox_Grid/*.html
            allure-reports/Ubuntu_Chrome_Grid/*.html
            allure-reports/Ubuntu_Edge_Grid/*.html
